### ISSUE TITLE
大佬建个qq群吧，方便反馈问题

### ISSUE THREAD

**Issue by singsongs7731** [SFHJavaer/R3nzSkinTencent#11]

**Comment by SFHJavaer** [comment]
这个暂时没有，因为开这个仓库是抱着学习的心态的，而且最近很忙，如果开群交流问题又要多干一份活，遇到解决不了的问题花的时间就更多了，谢谢理解

**Comment by SFHJavaer** [comment]
特征码失效等问题可以移步到 @hydy100 的仓库，我这里更新不及时
