### ISSUE TITLE
这个版本就是R3nzSkin未更新原版改了个偏移量(offset)吗

### ISSUE THREAD

**Issue by lhr42** [SFHJavaer/R3nzSkinTencent#14]

**Comment by SFHJavaer** [comment]
14.14的包改了一些模型的特征码

**Comment by AssassinTango** [comment]
> 14.14的包改了一些模型的特征码
看对比主要是修改了Champion的结构，想问下offset_signature是怎么生成的，以及大致是什么含义

**Comment by SFHJavaer** [comment]
> > 看对比主要是修改了Champion的结构，想问下offset_signature是怎么生成的，以及大致是什么含义
改Champion是因为vector接收不了就换成sdk里的对象了
offset_signature里放的都是特征码，特征码的作用就是你根据特征码能搜索到对应的操作指令串是唯一的，其实就是R3是通过特征码搜索基址来hook的，基址经常会变
怎么生成的？逆向的时候你找到基地址对应的MOV 寄存器的操作，一般来说往前找几条汇编操作指令所对应的，这几条汇编对应的字节数组就是特征码，不确定的用??代替，字节没有大更新一般是固定的，字节数组搜索不到了就说明有更新了

**Comment by SFHJavaer** [comment]
> > 看对比主要是修改了Champion的结构，想问下offset_signature是怎么生成的，以及大致是什么含义

改Champion是因为vector接收不了就换成sdk里的对象了
offset_signature里放的都是特征码，特征码的作用就是你根据特征码能搜索到对应的操作指令串是唯一的，其实就是R3是通过特征码搜索基址来hook的，基址经常会变
怎么生成的？逆向的时候你找到基地址对应的MOV 寄存器的操作，一般来说往前找几条汇编操作指令所对应的，这几条汇编对应的字节数组就是特征码，不确定的用??代替，字节没有大更新一般是固定的，字节数组搜索不到了就说明有更新了

**Comment by shy113** [comment]
我想问下如何逆向分析lol游戏内存😁
