### ISSUE TITLE
why i compile by myself，then the dill does not work？

### ISSUE THREAD

**Issue by DoubleQiany** [SFHJavaer/R3nzSkinTencent#19]

**Comment by SFHJavaer** [comment]
不能工作的具体表现是?

**Comment by zaqswr** [comment]
加载游戏的时候黑屏  进不去游戏啊姐

**Comment by zaqswr** [comment]
把HID.dll删了马上就能进了=-=

**Comment by jvbscy** [comment]
环境怎么配置

**Comment by SFHJavaer** [comment]
**解决方法**
打开【GeForce Experience】
点击右上方的【小齿轮】
![image](https://github.com/user-attachments/assets/4f13cf3b-cbb1-414d-b93b-d7ef4e3c9d3e)

找到【游戏内覆盖】，点击后面的【开关按钮】:
![image](https://github.com/user-attachments/assets/d85b9563-6607-4a41-9332-acd076a066ee)
重新进入游戏

**Comment by SFHJavaer** [comment]
> 环境怎么配置

支持vc++20标准的编译器版本均可

**Comment by zaqswr** [comment]
谢谢姐  得了

**Comment by jvbscy** [comment]
朋友说以前有具体的教程的&nbsp; 现在还有吗&nbsp; 直接gitclone到vs就行了吗&nbsp; 编译环境怎么操作 最后怎么变成hid.dll


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SFHJavaer/R3nzSkinTencent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月19日(星期一) 中午12:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SFHJavaer/R3nzSkinTencent] why i compile by myself，then the dill does not work？ (Issue #19)





 
谢谢姐  得了
