### ISSUE TITLE
请教下老哥每次国服更新该如何修改代码才能继续使用，大概讲一下就行

### ISSUE THREAD

**Issue by kdhj** [SFHJavaer/R3nzSkinTencent#2]

**Comment by SFHJavaer** [comment]
需要开CE或者IDA逆向，作者原版本原本就是防封的，14.11只是由于pattern模式变化了导致扫不到对应的内存地址，解决了内存地址变更的问题，自己修去看一下过期的偏移量是哪一个，根据哪一个过期的偏移量去找对应的变化方式自己去一遍一遍扫

比如，如果是皮肤找不到就在训练营换皮肤扫内存看skinid如何变化，如果是模型的内存地址错误，就不断重生或移动观察找到能和变化找到和模型关联起来的内存地址，作者维护了很长时间逆向的位置可以是信手拈来，如果是自己维护，有的地址找不到门路可能要debug‘一遍一遍逆向很久，而且改完封号情况未知，没那么多时间测试。

后续如果除了内存地址如果其他代码都有新版本适配问题，代码需要维护，那么就需要新的开源作者了，个人如果不是为了盈利而维护，得不偿失，因为现在R3nz没人维护了，能用的R3套壳成盒子拿去卖，除去前期开发的前端和服务器、推广费用，后续换肤就是一本万利的生意

所以如果是研究着玩，可以去B站学逆向

要是为了换肤，可以找部分开源的版本，但是有风险，原因是只有国服用的是腾讯自己的的TP，国人作者大多开收费盒子或闭源，如果能找到像原作者一样长期维护的国外开源作者可以

可以花几块钱买个收费的，界面还会更友好一些。

**Comment by SFHJavaer** [comment]
B站逆向基础看完，可以去LOL换肤吧和国外逆向论坛看换肤实现原理，要看懂作者代码的话就去搜代码看注释学C++，看完基本上应该能用的问题都能解决了，因为我现在也正在看

**Comment by laizizhongguoxiaobai** [comment]
怎么方式能联系到你呢,Q80895712

**Comment by kdhj** [comment]
谢谢老哥，老哥牛逼

**Comment by 21307369** [comment]
有没开个视频让我们抄作业啊?
