### ISSUE TITLE
Would you still be willing to update version 14.17

### ISSUE THREAD

**Issue by loveouyszl** [SFHJavaer/R3nzSkinTencent#24]
Would you still be willing to update version 14.17

**Comment by NavoNivalis** [comment]
有教程吗，不想麻烦作者了，这游戏更新挺频繁的

**Comment by SFHJavaer** [comment]
> 有教程吗，不想麻烦作者了，这游戏更新挺频繁的

不是不发出来教给你们，除了一些学院几k的收费课程之外，网上还没流传系统性改LOL的教程，自己搜索下有些很粗的教程也能看，但是也不是拿过来就能用的，而且逆向的内容很宽泛，B站就有一部分教程，学会了就可以同步到LOL上来，但是就算逆向学会了，还要考虑不同游戏的处理方式，不会过保护还要买驱动等等

空闲时间多且对逆向感兴趣，可以先把免费课程看一套，多逛一些论坛，加下逆向的交流群，从别的游戏逆向开始慢慢学，学习过程中你就发现你需要掌握什么东西了

不是逆向科班或者不能变现的，研究很深入了也意义不大，为了玩游戏去找一些开源作者的用就行，有些Github作者更新也蛮及时的，我看他们更新的都挺及时我后面就停更了
因为互联网就业环境比较差，玩游戏的时间都越来越少了，不过还是有很多作者愿意坚持分享还是蛮好的

**Comment by SFHJavaer** [comment]
有资源的可以分享出来，我手里也没有什么好的资源
