### ISSUE TITLE
14.17剑魔换肤会卡死

### ISSUE THREAD

**Issue by Deer-Cr** [SFHJavaer/R3nzSkinTencent#25]
目前只测试了武器和剑魔两个人    剑魔一换就卡闪退  不知道有没有其他英雄这样

**Comment by SFHJavaer** [comment]
没有测试全，我下午重新发布一版

如果大多数英雄都有问题，我先把release删掉

**Comment by yqyyds66** [comment]
@SFHJavaer 亲爱的作者我能添加一个你的联系方式吗 有时候有什么不懂得我想请教一下你

**Comment by SFHJavaer** [comment]
> @SFHJavaer 亲爱的作者我能添加一个你的联系方式吗 有时候有什么不懂得我想请教一下你 

有问题可以联系我首页的邮箱📭，我看到只要我知道的都会回复的
