### ISSUE TITLE
无法进入游戏

### ISSUE THREAD

**Issue by MoLu10086** [SFHJavaer/R3nzSkinTencent#29]
更换文件为hid.dll后，存放在LOL目录下，可以正常进入英雄联盟客户端，但无法进入到游戏内，一直处于黑屏状态

**Comment by SFHJavaer** [comment]
[Update encryption.hpp](https://github.com/SFHJavaer/R3nzSkinTencent/commit/c0197000890cc72f32dd7a1b811d7283c21d2df9)

**Comment by xslzlccc** [comment]
> [Update encryption.hpp](https://github.com/SFHJavaer/R3nzSkinTencent/commit/c0197000890cc72f32dd7a1b811d7283c21d2df9)

it not work

**Comment by SFHJavaer** [comment]
> > [Update encryption.hpp](https://github.com/SFHJavaer/R3nzSkinTencent/commit/c0197000890cc72f32dd7a1b811d7283c21d2df9)
> 
> it not work

黑屏 #19
