### ISSUE TITLE
开对局后就出现了进程无响应

### ISSUE THREAD

**Issue by UBIHHH** [SFHJavaer/R3nzSkinTencent#3]

**Comment by SFHJavaer** [comment]
1.确保hid.dll在国服配置方式正确
2.开无边框
3.加载辅助是会卡一下的，电脑配置足够忽略此条
4.系统兼容性问题，使用R3旧版本应当也存在该问题，检查兼容性及系统C++游戏依赖库

**Comment by UBIHHH** [comment]
我将hid.dll放入Game文件夹，也开启了无边框，但仍然是对局进程无响应。在4月之前我一直使用原作者的文件无任何问题。

**Comment by SFHJavaer** [comment]
可能是打的包和系统不兼容，目前环境都是win10-64位系统
尝试在属性里配置以兼容模式运行此程序，注意配置的是LOL游戏程序而不是LOLClient客户端程序

**Comment by SFHJavaer** [comment]
因为我本地的C++版本运行库之类和原作者不同，所以打出来的包有可能出现在不同电脑运行环境上的兼容性问题
