### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by DuckDuckDuck985** [SFHJavaer/R3nzSkinTencent#30]
现在只要有这个文件，进游戏就会自动的退出

**Comment by SFHJavaer** [comment]
用的14.17.001还是自己打包

**Comment by xslzlccc** [comment]
> 用的14.17.001还是自己打包

14.17.001和自己打包的都不行。

**Comment by SFHJavaer** [comment]
> > 用的14.17.001还是自己打包
> 
> 14.17.001和自己打包的都不行。

描述环境和报错原因或者报错现象，否则太笼统的不予回答
黑屏问题，参考 #19
