### ISSUE TITLE
大佬可以改下不要每次都自动加载 改成手动 按ins键呼出吗?

### ISSUE THREAD

**Issue by 21307369** [SFHJavaer/R3nzSkinTencent#31]
大佬可以改下不要每次都自动加载改成手动 按ins键呼出吗?

**Comment by SFHJavaer** [comment]
可以，不过每个人操作习惯不一样，如果这个issues下反馈这个问题的强迫症比较多，下次可以改一下~

**Comment by piggerL** [comment]
本强迫症+1

**Comment by 21307369** [comment]
主要是会卡下画面

**Comment by SFHJavaer** [comment]
> 主要是会卡下画面

这个和加载Gui的关系不大，是进泉水全局Hook的时候会卡顿一下，受电脑高低配置影响
后续删除一些无用逻辑看下能否修复或者优化，有优化好的代码可以直接提Pr
Gui加载顺序的问题，这几天再发下Release

**Comment by LyraHeartstrings17** [comment]
这个卡顿好像有概率直接卡死客户端，只能重启解决
