### ISSUE TITLE
马服版本更新了，求大佬更新😯

### ISSUE THREAD

**Issue by vinland100** [SFHJavaer/R3nzSkinTencent#33]
马服版本更新了，求大佬更新😯

**Comment by MoLu10086** [comment]
更新了也可以正常使用啊，我到现在还是用的目前的版本，依旧可以正常使用

**Comment by vinland100** [comment]
> 更新了也可以正常使用啊，我到现在还是用的目前的版本，依旧可以正常使用

ok，我试了一下确实可以
