### ISSUE TITLE
求大佬更新

### ISSUE THREAD

**Issue by a8980915** [SFHJavaer/R3nzSkinTencent#9]

**Comment by SFHJavaer** [comment]
最新的Release在**14.13**应该都是可用的

**目前只有以下几种情况会更新：**

- 游戏版本迭代导致地址更新：提示内存地址未找到
- 代码结构与游戏不再兼容了：闪退或崩溃提示或为未响应
- 特殊皮肤处理：个别皮肤功能性质不全，非渲染问题

对于版本更新：出新皮肤了，直接使用旧版本即可，原因是皮肤数据和英雄是绑定关系，皮肤更新了自动绑定到英雄上，无需更新

`报错的话直接上传错误截图，我会在周末查看及更新`

**Comment by hydy100** [comment]
AIMinionClient变了，离体单位的皮肤和修改小兵皮肤不生效。

**Comment by SFHJavaer** [comment]
> AIMinionClient变了，离体单位的皮肤和修改小兵皮肤不生效。

抱歉之前没注意到，而且最近很忙导致没时间去开调试。

开这个仓库原本是学习C++逆向和自己和现实朋友之间用
而且我看您也开了开源仓库，因为我也是处于学习阶段，会遇到无法解决的issues我会让其移步到您的仓库或R3讨论区，感谢

而且我附加调试的方式可能有些问题，调试中经常崩溃，有什么好的交流渠道可以指点我一下，谢谢

**Comment by hydy100** [comment]
> > AIMinionClient变了，离体单位的皮肤和修改小兵皮肤不生效。
> 
> 抱歉之前没注意到，而且最近很忙导致没时间去开调试。
> 
> 开这个仓库原本是学习C++逆向和自己和现实朋友之间用 而且我看您也开了开源仓库，因为我也是处于学习阶段，会遇到无法解决的issues我会让其移步到您的仓库或R3讨论区，感谢
> 
> 而且我附加调试的方式可能有些问题，调试中经常崩溃，有什么好的交流渠道可以指点我一下，谢谢

dump下来用IDA，或者用VT，或者Hook摘干净去保护再用修改版CE也能调试。
